### ISSUE TITLE
how to animate widgets just once?

### ISSUE THREAD

**Issue by roopa1712** [sharp3dges/animator#1]
I am trying to translate widget using fade in right.
But i want to do this only once.
While now i see that on tap of the widget the animation executes itself.

**Comment by sharp3dges** [comment]
Hi @roopa1712 ,

The answer is: by default animations only play once on the first widget's init. My guess is that your code accidentally re-adds the parent, creating an entirely new animation instance. Meaning animation is performed again.
Further more, please note animations replay once when hot-reload is performed.

You can set the specific play-mode (forward, loop, pingpong or reverse) by passing in an **AnimationPreferences** instance with the desired **AnimationPlayStates** enum.

If you want more control over when and how to run animations, you can also pass in a **GlobalKey**.
See below for an example.

Example: More control by passing a GlobalKey.
```dart
class MyHomePage extends StatelessWidget {
  ///Use a GlobalKey to gain access to the [AnimatorWidgetState],
  ///every animated widget from the flutter_animator package uses this state.
  final GlobalKey<AnimatorWidgetState> _animationKey =
      GlobalKey<AnimatorWidgetState>();

  MyHomePage();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Animate once'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: <Widget>[
            FadeInRight(
                ///We pass in the _animationKey to control our animation
                key: _animationKey,
                preferences: AnimationPreferences(
                  autoPlay: AnimationPlayStates.None,
                ),
                child: Text(
                  'FadeInRight',
                  textAlign: TextAlign.center,
                )),
            FloatingActionButton(
              onPressed: () {
                ///Animate forward once, using the _animationKey supplied
                ///to the BounceInDownWidget above.
                _animationKey.currentState.forward();
              },
              child: Text('Animate Once'),
            )
          ],
        ),
      ),
    );
  }
}
```

You could also keep track of a shouldAnimate boolean in a parent statefull widget and pass in the **AnimationPlayStates** enum accordingly.

If the above example does not work for you, please supply some code so I can help you further.
Just reopen the issue if problems persist.

Good luck! 


Kind regards,

Sjoerd van den Berg.
