### ISSUE TITLE
AnimationPreferences bug with autoPlay PingPong

### ISSUE THREAD

**Issue by alexgtn** [sharp3dges/animator#6]
I have set AnimationPreferences

```
RollIn(
  child: Image.asset(
    "assets/asset.png",
  ),
  preferences: AnimationPreferences(
    autoPlay: AnimationPlayStates.PingPong,
  ),
),
```

`AnimationPlayStates.Loop` and `AnimationPlayStates.PingPong` behave exactly the same. There is no forward and reverse behaviour for PingPong

**Comment by sharp3dges** [comment]
Hi @alexgtn, you are right.
I have fixed this, it should be working from `flutter_animator: 3.1.2`

Could you let me know if this resolves your issue?

**Comment by alexgtn** [comment]
@sharp3dges Thank you! Works as expected! Can be closed.
