### ISSUE TITLE
How to adjust the animation distance？

### ISSUE THREAD

**Issue by LiangLuDev** [sharp3dges/animator#7]
use 「FadeInUp」，The animation distance is a bit long

**Comment by sharp3dges** [comment]
> use 「FadeInUp」，The animation distance is a bit long

Hi LiangLuDev,

The distance is currently not directly adjustable.
I will look into this when I have time, I am currently on vacation though so I'm afraid I can't do this anytime soon.
You could create your own implementation and create a PR if you need it now.

**Comment by aytunch** [comment]
@sharp3dges Hi,

I was going to open up a similar issue. I want to have control over the magnitude of the animations. Let's say the defaults are 1.0

If we set a new variable called magnitude to 0.5 the x and y values will be halved and if we set it to 2 it will double


Also some animations like 'Shake' need to have the horizontal, vertical and both options imho.

Using this package is extremely user friendly and thanks for your effort. Some extra customization would make life a lot easier for us.

Have a great vacation bro

**Comment by sharp3dges** [comment]
@LiangLuDev , @aytunch : Thank you for reporting this.
Sorry for taking so long, I just updated the package to version 3.2.0

This includes the magnitude property inside the AnimationPreferences (which can be passed into the animated widgets) to control the animation magnitude.

Let me know if you experience any issues. (Also if this works to your liking so we can close this issue ;) )

Kind regards.

**Comment by LiangLuDev** [comment]
@sharp3dges Hi guy !
Thank you very much for sharing. Is it convenient to exchange contact information and make a friend?
